version: '3.7'

services:
  app:
    image: backend:v1
    restart: always
    ports:
      - "82:82"
    volumes:
      - ./docker_application.properties:/app/application.properties:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    volumes:
      - ./.docker/data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 05062004
      MYSQL_DATABASE: ecommercedbtest
